server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://training-kyle-p.cvtq9j4axrge.us-east-1.rds.amazonaws.com:5432/Revvi
    driver-class-name: org.postgresql.Driver
    username: revvi
    password: qZmRtLA717A
  h2:
    console.enabled: true
